"""Single source of truth for the Astra robot kinematics.

The canonical model is the standard-DH table in ``create_astra_dh`` (which is
RoboDK-validated and drives the URDF + web-viewer manifest).  Everything else
must be **derived** from it — never hand-entered again:

  * ``dh_to_poe()`` derives the base-frame PoE (screw pivots, axes, home M)
    used by the Python and JavaScript PoE solvers.
  * ``poe_to_js()`` renders those constants as JavaScript source text, so the
    embedded viewer's ``astra_kinematics.js`` is generated — killing the old
    hand-duplicated PoE constants that disagreed with the DH tool orientation.
  * ``verify_models()`` asserts DH FK == PoE FK == dual-quaternion FK across
    random joint angles, so any drift between representations fails loudly.
"""

from __future__ import annotations

from typing import List, Sequence

import numpy as np

from . import dual_quaternion as _dq
from . import poe_kinematics as _poe

# Canonical joint names / link names (must match build_nite369_urdf.py).
JOINT_NAMES = ["j1", "j2", "j3", "j4", "j5", "j6"]
LINK_NAMES = ["base", "link1", "link2", "link3", "link4", "link5", "link6"]


def get_astra_arm():
    """Return the canonical Astra DH arm (create_astra_dh)."""
    from .kinematics import create_astra_dh
    return create_astra_dh()


def dh_table_dict(arm=None) -> List[dict]:
    """The canonical DH table as a list of per-joint dicts."""
    if arm is None:
        arm = get_astra_arm()
    table = []
    for i, p in enumerate(arm.dh_params):
        name = arm.joint_names[i] if i < len(arm.joint_names) else ""
        limits = arm.joint_limits.get(name, (-np.pi, np.pi))
        table.append({
            "name": name,
            "a": float(p.a),
            "alpha": float(p.alpha),
            "d": float(p.d),
            "theta_offset": float(p.theta_offset),
            "limits": [float(limits[0]), float(limits[1])],
            "gear_ratio": float(arm.gear_ratios.get(name, 1.0)),
            "home": float(arm.home_position.get(name, 0.0)),
        })
    return table


def dh_to_poe(arm=None):
    """Derive (pivots, axes, home_4x4) from the canonical DH arm.

    Returns the same quantities the JS viewer used to hard-code as
    ``POE_PIVOTS`` / ``POE_AXES`` / ``POE_HOME``.
    """
    if arm is None:
        arm = get_astra_arm()
    model = _poe.poe_from_dh_arm(arm)
    return model.pivots.tolist(), model.axes.tolist(), model.home.tolist()


def poe_to_js(arm=None, indent=2) -> str:
    """Render the PoE constants as JavaScript source for the viewer.

    Produces a self-contained snippet defining ``POE_PIVOTS``, ``POE_AXES``
    and the home pose split into ``POE_HOME_ROT`` / ``POE_HOME_POS`` (the
    exact names the upgraded viewer's JS math references), all derived from
    the canonical DH table, so ``astra_kinematics.js`` (generated) and the
    hand-written JS math stay consistent by construction.
    """
    pivots, axes, home = dh_to_poe(arm)
    home = np.asarray(home, dtype=float)
    def _fmt(v):
        return "%.9f" % v
    lines = [
        "// Generated by astra_kinematics.dh_to_poe() from create_astra_dh().",
        "// DO NOT EDIT — regenerate with tools/build_kinematics_assets.py.",
        "// Attached to globalThis so the constants are visible to the viewer",
        "// math and to eval()-based tests/round-trips.",
        "const POE_PIVOTS = [",
    ]
    for p in pivots:
        lines.append("  [%s, %s, %s]," % tuple(_fmt(x) for x in p))
    lines.append("];")
    lines.append("const POE_AXES = [")
    for a in axes:
        lines.append("  [%s, %s, %s]," % tuple(_fmt(x) for x in a))
    lines.append("];")
    rot = home[:3, :3]
    pos = home[:3, 3]
    lines.append("const POE_HOME_ROT = [")
    for r in rot:
        lines.append("  [%s, %s, %s]," % tuple(_fmt(x) for x in r))
    lines.append("];")
    lines.append("const POE_HOME_POS = [%s, %s, %s];" % tuple(_fmt(x) for x in pos))
    lines += [
        "globalThis.POE_PIVOTS = POE_PIVOTS;",
        "globalThis.POE_AXES = POE_AXES;",
        "globalThis.POE_HOME_ROT = POE_HOME_ROT;",
        "globalThis.POE_HOME_POS = POE_HOME_POS;",
    ]
    return "\n".join(lines) + "\n"


def verify_models(arm=None, samples: int = 100, tol: float = 1e-9,
                  rng=None) -> dict:
    """Cross-validate DH FK == PoE FK == dual-quaternion FK.

    Args:
        arm: the DH arm (defaults to create_astra_dh()).
        samples: number of random joint-angle poses to test.
        tol: per-element tolerance on transform equality.
        rng: numpy RandomState (defaults to a fixed seed).

    Returns:
        dict with keys 'max_dh_poe', 'max_dh_dq', 'max_poe_dq' (max abs
        elementwise difference over all samples).

    Raises:
        AssertionError if any model disagrees beyond ``tol``.
    """
    if arm is None:
        arm = get_astra_arm()
    if rng is None:
        rng = np.random.RandomState(42)
    model = _poe.poe_from_dh_arm(arm)
    n = arm.num_joints
    max_dh_poe = 0.0
    max_dh_dq = 0.0
    max_poe_dq = 0.0
    for _ in range(samples):
        thetas = rng.uniform(-np.pi, np.pi, size=n)
        T_dh = arm.forward(thetas)
        T_poe = model.fk_4x4(thetas)
        T_dq = _dq.dual_quaternion_fk_arm(arm, thetas)
        max_dh_poe = max(max_dh_poe, float(np.abs(T_dh - T_poe).max()))
        max_dh_dq = max(max_dh_dq, float(np.abs(T_dh - T_dq).max()))
        max_poe_dq = max(max_poe_dq, float(np.abs(T_poe - T_dq).max()))

    result = {
        "max_dh_poe": max_dh_poe,
        "max_dh_dq": max_dh_dq,
        "max_poe_dq": max_poe_dq,
    }
    assert max_dh_poe < tol, "DH vs PoE FK diverged: %g" % max_dh_poe
    assert max_dh_dq < tol, "DH vs dual-quaternion FK diverged: %g" % max_dh_dq
    assert max_poe_dq < tol, "PoE vs dual-quaternion FK diverged: %g" % max_poe_dq
    return result


def home_pose_mm(arm=None) -> np.ndarray:
    """Tool position at home, in millimetres."""
    if arm is None:
        arm = get_astra_arm()
    return arm.forward([0.0] * arm.num_joints)[:3, 3] * 1000.0


def home_pose_js(arm=None) -> str:
    """The JS home-constants block, generated from the DH home pose."""
    if arm is None:
        arm = get_astra_arm()
    model = _poe.poe_from_dh_arm(arm)
    h = model.home
    rot = h[:3, :3]
    pos = h[:3, 3]
    return (
        "const POE_HOME_ROT = [\n"
        "  [%.9f, %.9f, %.9f],\n"
        "  [%.9f, %.9f, %.9f],\n"
        "  [%.9f, %.9f, %.9f],\n"
        "];\n"
        "const POE_HOME_POS = [%.9f, %.9f, %.9f];\n"
        % (rot[0, 0], rot[0, 1], rot[0, 2],
           rot[1, 0], rot[1, 1], rot[1, 2],
           rot[2, 0], rot[2, 1], rot[2, 2],
           pos[0], pos[1], pos[2])
    )
