# version.cmake — auto-increment build version on every build.
#
# Reads a counter file (build_count.txt), increments it, and writes
# ${BINARY_DIR}/firmware_version.h containing:
#   #define FIRMWARE_VERSION_STR "1.003"
#   #define FIRMWARE_BUILD_COUNT 3
# The header is regenerated on every build, so each uf2 has a unique
# version. Point this script at your counter file:
#   cmake -D VERSION_COUNTER_FILE=<path> -D VERSION_HEADER_OUT=<path>
#        -P version.cmake

if(NOT DEFINED VERSION_COUNTER_FILE)
    message(FATAL_ERROR "VERSION_COUNTER_FILE not set")
endif()
if(NOT DEFINED VERSION_HEADER_OUT)
    message(FATAL_ERROR "VERSION_HEADER_OUT not set")
endif()

set(count 0)
if(EXISTS "${VERSION_COUNTER_FILE}")
    file(READ "${VERSION_COUNTER_FILE}" count_str)
    string(STRIP "${count_str}" count_str)
    if(count_str MATCHES "^[0-9]+$")
        math(EXPR count "${count_str}" )
    endif()
endif()

math(EXPR count "${count} + 1")

# Version = 1.XXX where XXX = build count (1.001, 1.002, ...)
math(EXPR minor "${count}")
string(LENGTH "${minor}" len)
set(ver "1.000")
if(len EQUAL 1)
    set(ver "1.00${minor}")
elseif(len EQUAL 2)
    set(ver "1.0${minor}")
else()
    set(ver "1.${minor}")
endif()

file(WRITE "${VERSION_HEADER_OUT}"
"/* Auto-generated by version.cmake — DO NOT EDIT. */\n"
"#ifndef FIRMWARE_VERSION_H\n"
"#define FIRMWARE_VERSION_H\n"
"#define FIRMWARE_VERSION_STR \"${ver}\"\n"
"#define FIRMWARE_BUILD_COUNT ${count}\n"
"#endif\n")

file(WRITE "${VERSION_COUNTER_FILE}" "${count}")
message(STATUS "Version bumped to ${ver} (build ${count})")
