from .base import BasePostProcessor
from ..programming import MoveType


class AbbPostProcessor(BasePostProcessor):
    name = "abb"
    extension = ".mod"
    description = "ABB RAPID (.mod)"

    def convert(self, program):
        lines = [
            f"MODULE {program.name[:32]}",
            "",
            f"    ! {program.description}" if program.description else "",
            "    ! Generated by Astra Studio",
            "",
            "    PROC main()",
        ]
        for step in program.steps:
            if step.comment:
                lines.append(f"        ! {step.comment}")
            if step.type == MoveType.HOME:
                lines.append('        MoveAbsJ [[0,0,0,0,0,0], [9E9,9E9,9E9,9E9,9E9,9E9]], v100, fine, tool0;')
            elif step.type == MoveType.JOINT:
                joints = self._format_joints(step.targets)
                lines.append(f'        MoveAbsJ [[{joints}], [9E9,9E9,9E9,9E9,9E9,9E9]], v{int(step.speed)*10}, fine, tool0;')
            elif step.type == MoveType.LINEAR:
                joints = self._format_joints(step.targets)
                lines.append(f'        MoveJ [[{joints}], [9E9,9E9,9E9,9E9,9E9,9E9]], v{int(step.speed)*10}, fine, tool0;')
            elif step.type == MoveType.GRIPPER:
                if step.gripper:
                    lines.append("        GripperOpen;")
                else:
                    lines.append("        GripperClose;")
            elif step.type == MoveType.DELAY:
                lines.append(f"        WaitTime {step.delay};")
            elif step.type == MoveType.IO:
                lines.append(f"        SetDO do{step.io_pin}, {'TRUE' if step.io_state else 'FALSE'};")
        lines.append("    ENDPROC")
        lines.append("ENDMODULE")
        return self.line_end.join(lines)
