class BasePostProcessor:
    """Base class for robot program exporters."""

    name = "base"
    extension = ".txt"
    description = "Base post-processor"

    def __init__(self):
        self.header_comment = "; Generated by Astra Studio"
        self.line_end = "\n"

    def convert(self, program):
        """Convert a RobotProgram to target format string."""
        raise NotImplementedError

    def save(self, program, path):
        output = self.convert(program)
        with open(path, "w") as f:
            f.write(output)

    def _format_joints(self, joints, decimals=4):
        return ", ".join(f"{j:.{decimals}f}" for j in joints)

    def _escape_comment(self, text):
        return text
