from .base import BasePostProcessor
from ..programming import MoveType


class FanucPostProcessor(BasePostProcessor):
    name = "fanuc"
    extension = ".ls"
    description = "FANUC Karel (.ls)"

    def convert(self, program):
        lines = [
            f"! {program.name}",
            "! Generated by Astra Studio Pro",
            "",
            f"PROGRAM {program.name[:24].upper()}"
        ]
        lines.append("  VAR")
        lines.append("    joint_pos : ARRAY[6] OF REAL")
        lines.append("  BEGIN")
        lines.append("")

        for step in program.steps:
            if step.comment:
                lines.append(f"    ! {step.comment}")
            if step.type == MoveType.HOME:
                lines.append("    joint_pos = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]")
                lines.append("    CALL MOVE_J(joint_pos)")
            elif step.type == MoveType.JOINT:
                joints = self._format_joints(step.targets)
                lines.append(f"    joint_pos = [{joints}]")
                lines.append(f"    CALL MOVE_J(joint_pos)  ; speed={step.speed:.0f}%")
            elif step.type == MoveType.LINEAR:
                joints = self._format_joints(step.targets)
                lines.append(f"    joint_pos = [{joints}]")
                lines.append(f"    CALL MOVE_L(joint_pos)  ; speed={step.speed:.0f}%")
            elif step.type == MoveType.GRIPPER:
                if step.gripper:
                    lines.append("    CALL GRIPPER_OPEN")
                else:
                    lines.append("    CALL GRIPPER_CLOSE")
            elif step.type == MoveType.DELAY:
                lines.append(f"    DELAY({step.delay:.1f})")
            elif step.type == MoveType.IO:
                lines.append(f"    DO[{step.io_pin}]={'ON' if step.io_state else 'OFF'}")

        lines.append("")
        lines.append(f"  END {program.name[:24].upper()}")
        return self.line_end.join(lines)
