from .base import BasePostProcessor
from ..programming import MoveType


class KukaPostProcessor(BasePostProcessor):
    name = "kuka"
    extension = ".src"
    description = "KUKA KRL (.src)"

    def convert(self, program):
        lines = [
            f"&ACCESS RVP",
            "&REL 1",
            f"&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\template",
            f"&PARAM EDITMASK = *",
            f"DEF {program.name[:24]}( )",
            f"; {program.description}" if program.description else "",
            "; Generated by Astra Studio Pro",
            "",
            "BAS(#INITMOV,0)",
            "",
        ]
        lines = [l for l in lines if l]

        step_num = 0
        for step in program.steps:
            step_num += 1
            if step.comment:
                lines.append(f"; {step.comment}")
            if step.type == MoveType.HOME:
                lines.append(f"  PTP {{A1 0, A2 0, A3 0, A4 0, A5 0, A6 0}} C_PTP")
            elif step.type == MoveType.JOINT:
                joints = "A1 {}, A2 {}, A3 {}, A4 {}, A5 {}, A6 {}".format(
                    *[f"{j:.4f}" for j in step.targets]
                )
                lines.append(f"  PTP {{{joints}}} C_PTP Vel={step.speed:.0f}%")
            elif step.type == MoveType.LINEAR:
                joints = "A1 {}, A2 {}, A3 {}, A4 {}, A5 {}, A6 {}".format(
                    *[f"{j:.4f}" for j in step.targets]
                )
                lines.append(f"  LIN {{{joints}}} C_DIS Vel={step.speed:.0f}%")
            elif step.type == MoveType.CIRCULAR:
                joints = "A1 {}, A2 {}, A3 {}, A4 {}, A5 {}, A6 {}".format(
                    *[f"{j:.4f}" for j in step.targets]
                )
                lines.append(f"  CIRC {{{joints}}} C_DIS")
            elif step.type == MoveType.GRIPPER:
                lines.append(f"  OUT(1, {'TRUE' if step.gripper else 'FALSE'})")
                lines.append(f"  WAIT SEC 0.5")
            elif step.type == MoveType.DELAY:
                lines.append(f"  WAIT SEC {step.delay:.2f}")
            elif step.type == MoveType.IO:
                lines.append(f"  OUT({step.io_pin}, {'TRUE' if step.io_state else 'FALSE'})")

        lines.append("")
        lines.append("END")
        return self.line_end.join(lines)
