from .base import BasePostProcessor
from ..programming import MoveType


class MitsubishiPostProcessor(BasePostProcessor):
    name = "mitsubishi"
    extension = ".prg"
    description = "Mitsubishi MELFA (.prg)"

    def convert(self, program):
        lines = [
            f"' {program.name}",
            "' Generated by Astra Studio",
            f'Program {program.name[:16]}',
            '',
        ]
        for step in program.steps:
            if step.comment:
                lines.append(f"' {step.comment}")
            if step.type == MoveType.HOME:
                lines.append('  GoHome')
            elif step.type == MoveType.JOINT:
                joints = self._format_joints(step.targets)
                lines.append(f'  Mov J({joints})')
            elif step.type == MoveType.LINEAR:
                joints = self._format_joints(step.targets)
                lines.append(f'  Mov L({joints})')
            elif step.type == MoveType.GRIPPER:
                lines.append('  HOpen 1' if step.gripper else '  HClose 1')
            elif step.type == MoveType.DELAY:
                lines.append(f'  Wait {step.delay}')
            elif step.type == MoveType.IO:
                lines.append(f'  M_Out({step.io_pin}, {"1" if step.io_state else "0"})')
        lines.append('End')
        return self.line_end.join(lines)
