from .base import BasePostProcessor
from ..programming import MoveType


class URPostProcessor(BasePostProcessor):
    name = "ur"
    extension = ".script"
    description = "Universal Robots (.script)"

    def convert(self, program):
        lines = [
            f"# {program.name}",
            "# Generated by Astra Studio",
            "",
            "def astra_prog():",
        ]
        indent = "  "
        for step in program.steps:
            if step.comment:
                lines.append(f"{indent}# {step.comment}")
            if step.type == MoveType.HOME:
                lines.append(f'{indent}movej([0,0,0,0,0,0], a=1.2, v=0.25)')
            elif step.type == MoveType.JOINT:
                joints = self._format_joints(step.targets)
                v = step.speed / 100.0 * 1.5
                lines.append(f'{indent}movej([{joints}], a=1.2, v={v:.3f})')
            elif step.type == MoveType.LINEAR:
                joints = self._format_joints(step.targets)
                v = step.speed / 100.0 * 0.5
                lines.append(f'{indent}movel([{joints}], a=1.2, v={v:.3f})')
            elif step.type == MoveType.GRIPPER:
                if step.gripper:
                    lines.append(f"{indent}set_digital_out(8, True)")
                else:
                    lines.append(f"{indent}set_digital_out(8, False)")
            elif step.type == MoveType.DELAY:
                lines.append(f"{indent}sleep({step.delay})")
            elif step.type == MoveType.IO:
                lines.append(f"{indent}set_digital_out({step.io_pin}, {'True' if step.io_state else 'False'})")
        lines.append("end")
        return self.line_end.join(lines)
